import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import './globals.css'
import '../sass/index.sass'
import React from 'react'
import Providers from './providers'
import Package from '../../package.json'

// 1. import `NextUIProvider` component

export const metadata: Metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
}

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode
}>) {
 return (
  <html lang="en">
   <body className={GeistSans.className}>
    <Providers>{children}</Providers>
    <footer className="test-white absolute bottom-0 w-screen flex justify-center">
     Build v{Package.version}
    </footer>
   </body>
  </html>
 )
}
